using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;

namespace USB
{
    //2020.12.29 有些问题,目前只能检测到是否连接
    public class ID_FprCap
    {
        private const string DLLPath = @"ID_FprCap.dll";

        /// <summary>
        /// 连接设备
        /// </summary>
        /// <returns></returns>
        [DllImport(DLLPath, EntryPoint = "LIVESCAN_Init", CallingConvention = CallingConvention.StdCall)]
        public static extern int LIVESCAN_Init();

        /// <summary>
        /// 关闭设备
        /// </summary>
        /// <returns></returns>
        [DllImport(DLLPath, EntryPoint = "LIVESCAN_Close", CallingConvention = CallingConvention.StdCall)]
        public static extern int LIVESCAN_Close();



        /// <summary>
        /// 对话框
        /// </summary>
        /// <returns></returns>
        [DllImport(DLLPath, EntryPoint = "LIVESCAN_Setup", CallingConvention = CallingConvention.StdCall)]
        public static extern int LIVESCAN_Setup();
        /// <summary>
        /// 版本号
        /// </summary>
        /// <returns></returns>
        [DllImport(DLLPath, EntryPoint = "LIVESCAN_GetVersion", CallingConvention = CallingConvention.StdCall)]
        public static extern int LIVESCAN_GetVersion();

        /// <summary>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        /// 获取通道数量
        /// </summary>
        /// <returns></returns>
        [DllImport(DLLPath, EntryPoint = "LIVESCAN_GetChannelCount", CallingConvention = CallingConvention.StdCall)]
        public static extern int LIVESCAN_GetChannelCount();

        /// <summary>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        /// 设置采集器亮度
        /// </summary>
        /// <returns></returns>
        [DllImport(DLLPath, EntryPoint = "LIVESCAN_SetBright", CallingConvention = CallingConvention.StdCall)]
        public static extern int LIVESCAN_SetBright(int nChannel, int nBright);

        /// <summary>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        /// 设置采集器当前对比度
        /// </summary>
        /// <returns></returns>
        [DllImport(DLLPath, EntryPoint = "IVESCAN_SetContrast", CallingConvention = CallingConvention.StdCall)]
        public static extern int IVESCAN_SetContrast (int nChannel, int nContrast);


        /// <summary>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        /// 获得采集器当前的亮度
        /// </summary>
        /// <returns>=AM_E_SUCCESS 表示成功，<0表示错误码</returns>
        [DllImport(DLLPath, EntryPoint = "LIVESCAN_GetBright", CallingConvention = CallingConvention.StdCall)]
        public static unsafe extern int LIVESCAN_GetBright(int nChannel, [MarshalAs(UnmanagedType.VBByRefStr)] ref int  pnBright);

        /// <summary>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        ///获得采集器当前对比度
        /// </summary>
        /// <returns></returns>
        [DllImport(DLLPath, EntryPoint = "LIVESCAN_GetContrast", CallingConvention = CallingConvention.StdCall)]
        public static unsafe extern int LIVESCAN_GetContrast(int nChannel, [MarshalAs(UnmanagedType.VBByRefStr)] ref int pnContrast);



        /// <summary>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        ///获得采集器采集图像的宽度、高度的最大值
        /// </summary>
        /// <returns></returns>
        [DllImport(DLLPath, EntryPoint = "LIVESCAN_GetMaxImageSize", CallingConvention = CallingConvention.StdCall)]
        public static unsafe extern int LIVESCAN_GetMaxImageSize(int nChannel, int* pnWidth,int* pnHeight);


        /// <summary>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        ///获得采集器采集图像的宽度、高度的最大值
        /// </summary>
        /// <returns></returns>
        [DllImport(DLLPath, EntryPoint = "LIVESCAN_GetCaptWindow", CallingConvention = CallingConvention.StdCall)]
        public static unsafe extern int LIVESCAN_GetCaptWindow(int nChannel, int* pnOriginX, int* pnOriginY, int* pnWidth, int* pnHeight);

        /// <summary>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        ///设置当前图像的采集 位置、宽度和高度
        /// </summary>
        /// <returns></returns>
        [DllImport(DLLPath, EntryPoint = "LIVESCAN_SetCaptWindow", CallingConvention = CallingConvention.StdCall)]
        public static unsafe extern int LIVESCAN_SetCaptWindow(int nChannel, int nOriginX,int nOriginY, int nWidth, int nHeight);


        /// <summary>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        ///准备采集一帧图像
        /// </summary>
        /// <returns></returns>
        [DllImport(DLLPath, EntryPoint = "LIVESCAN_BeginCapture", CallingConvention = CallingConvention.StdCall)]
        public static unsafe extern int LIVESCAN_BeginCapture(int nChannel);


        /// <summary>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        ///采集一帧图像
        /// </summary>
        /// <returns></returns>
        [DllImport(DLLPath, EntryPoint = "LIVESCAN_GetFPRawData", CallingConvention = CallingConvention.StdCall)]
        public static unsafe extern int LIVESCAN_GetFPRawData(int nChannel, [MarshalAs(UnmanagedType.VBByRefStr)] ref string  pRawData);


        /// <summary>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        ///采集一帧BMP 格式图像数据
        /// </summary>
        /// <returns></returns>
        [DllImport(DLLPath, EntryPoint = "LIVESCAN_GetFPBmpData", CallingConvention = CallingConvention.StdCall)]
        public static unsafe extern int LIVESCAN_GetFPBmpData(int nChannel, char* pBmpData);

        /// <summary>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        ///结束采集一帧图像
        /// </summary>
        /// <returns></returns>
        [DllImport(DLLPath, EntryPoint = "LIVESCAN_EndCapture", CallingConvention = CallingConvention.StdCall)]
        public static unsafe extern int LIVESCAN_EndCapture(int nChannel);

        /// <summary>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        ///采集器是否支持设置对话框
        /// </summary>
        /// <returns></returns>
        [DllImport(DLLPath, EntryPoint = "LIVESCAN_IsSupportSetup", CallingConvention = CallingConvention.StdCall)]
        public static unsafe extern int LIVESCAN_IsSupportSetup();

        /// <summary>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        ///获得采集接口错误信息
        /// </summary>
        /// <returns></returns>
        [DllImport(DLLPath, EntryPoint = "LIVESCAN_GetErrorInfo", CallingConvention = CallingConvention.StdCall)]
        public static unsafe extern int LIVESCAN_GetErrorInfo(int nErrorNo, char pszErrorInfo);

        public static Dictionary<int, string> Code = new Dictionary<int, string>()
        {
            {-1,"参数错误" },
            {-2,"内存分配失败，没有分配到足够的内存" },
            {-3,"功能未实现" },
            {-4,"设备不存在" },
            {-5,"设备未初始化" },
            {-6,"非法错误号" },
            {-9,"其它错误" }
        };
    }
}
